version: '3.3'

services:
  influxdb:
    build: influxdb
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    build: grafana
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
  sonar:
    build: sonarclient
    env_file: configuration.env
    links:
      - influxdb
  
volumes:
  grafana_data: {}
  influxdb_data: {}
