{
 "title": "SonarResults",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Component",
    "query": "SHOW TAG VALUES WITH KEY = \"key\""
   }
  ]
 },
 "panels": [
  {
   "title": "Coverage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"coverage\" WHERE (\"key\" =~ /^$Application$/)  order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coverage  (Evaluation)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM coverage WHERE (\"key\" =~ /^$Application$/)  order by time desc  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"code_smells\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"critical_violations\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1\n\t ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocker",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"blocker_violations\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1\n\t ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"minor_violations\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1\n\t ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Major",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"major_violations\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"info_violations\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1\n\t ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Branch Coverage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"branch_coverage\" WHERE (\"key\" =~ /^$Application$/)  order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lines of Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"ncloc\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BIG FUNCTIONS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"CXX-BIG_FUNCTIONS\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duplicated Lines",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"duplicated_lines\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lines to Cover",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"lines_to_cover\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Code Smells  (Evaluation)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM code_smells WHERE (\"key\" =~ /^$Application$/)  order by time desc  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Line Coverage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"line_coverage\" WHERE (\"key\" =~ /^$Application$/)  order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Complexity",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"complexity\" WHERE (\"key\" =~ /^$Application$/) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duplicated Lines Density",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"duplicated_lines_density\" WHERE (\"key\" =~ /^$Application$/)  order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}